-- Diff code generated with pgModeler (PostgreSQL Database Modeler)
-- pgModeler version: 1.0.5
-- Diff date: 2023-07-28 13:11:53
-- Source model: library
-- Database: library
-- PostgreSQL version: 15.0

-- [ Diff summary ]
-- Dropped objects: 0
-- Created objects: 2
-- Changed objects: 0

SET search_path=public,pg_catalog,library;
-- ddl-end --


-- [ Created objects ] --
-- object: library | type: SCHEMA --
-- DROP SCHEMA IF EXISTS library CASCADE;
CREATE SCHEMA IF NOT EXISTS library;
-- ddl-end --
ALTER SCHEMA library OWNER TO db_owner;
-- ddl-end --

-- object: library.book | type: TABLE --
-- DROP TABLE IF EXISTS library.book CASCADE;
CREATE TABLE library.book (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	title text NOT NULL,
	author text NOT NULL,
	publisher text NOT NULL,
	year_published integer,
	CONSTRAINT book_pk PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE library.book OWNER TO db_owner;
-- ddl-end --



-- [ Created permissions ] --
-- object: "grant_c*_342d67355a" | type: PERMISSION --
GRANT CONNECT
   ON DATABASE library
   TO db_reader WITH GRANT OPTION;
-- ddl-end --

-- object: "grant_c*_4dd2cadb77" | type: PERMISSION --
GRANT CONNECT
   ON DATABASE library
   TO db_writer WITH GRANT OPTION;
-- ddl-end --

-- object: "grant_r*x*t*_ce40070e41" | type: PERMISSION --
GRANT SELECT,REFERENCES,TRIGGER
   ON TABLE library.book
   TO db_reader WITH GRANT OPTION;
-- ddl-end --

-- object: "grant_r*a*w*d*x*t*_bda45b23c4" | type: PERMISSION --
GRANT SELECT,INSERT,UPDATE,DELETE,REFERENCES,TRIGGER
   ON TABLE library.book
   TO db_writer WITH GRANT OPTION;
-- ddl-end --

